version: "3.9"
services:
  envoy-gateway-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.kube:/root/.kube:ro
    ports:
      - "8080:8080"
    environment:
      - DD_EXTENSION=true
      - NODE_ENV=production
