FROM node:18-alpine

WORKDIR /app
COPY envoy-gateway-extension/backend-new/package.json envoy-gateway-extension/backend-new/package-lock.json ./
RUN npm ci

COPY envoy-gateway-extension/backend-new/dist ./dist
COPY envoy-gateway-extension/backend-new/node_modules ./node_modules

ENV DD_EXTENSION=true
ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080
CMD ["node", "dist/index.js"]
