version: '3.8'

services:
  envoy-gateway-extension:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - LOG_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/app/src
      - ./docs:/app/docs
    networks:
      - envoy-gateway-network

  # Example backend service for testing
  sample-backend:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./examples/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - envoy-gateway-network

  # Jaeger for tracing (optional)
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - envoy-gateway-network

  # Prometheus for metrics (optional)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./examples/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - envoy-gateway-network

networks:
  envoy-gateway-network:
    driver: bridge

volumes:
  envoy-data:
