apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
metadata:
  type: Full
  name: envoy-gateway-config
spec:
  gateway:
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
  provider:
    type: Kubernetes
  logging:
    level:
      default: info
  admin:
    address:
      host: 0.0.0.0
      port: 19000
  telemetry:
    metrics:
      prometheus:
        disable: false
    tracing:
      providers:
        - name: jaeger
          type: jaeger
