services:
  backend:
    image: ${DESKTOP_PLUGIN_IMAGE}
    restart: always
    command: ["node", "/app/dist/index.js"]
    volumes:
      - type: bind
        source: ~/.kube/config
        target: /root/.kube/config
        read_only: true
    environment:
      - DD_EXTENSION=true
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
