version: '3.8'
services:
  envoy-gateway-service:
    image: ${DESKTOP_PLUGIN_IMAGE}
    restart: always
    ipc: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/guest-services:/run/guest-services:rw
      - ${HOME}/.kube:/root/.kube:ro
    environment:
      - DD_EXTENSION=true
      - NODE_ENV=production
      - SOCKET_PATH=/run/guest-services/extension-envoy-gateway-extension.sock
    privileged: true

