version: '3.8'
services:
  envoy-gateway-backend:
    image: ${DESKTOP_PLUGIN_IMAGE}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SOCKET_PATH=/tmp/backend.sock
    networks:
      - default
